# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  apt_packages:
    - libldap2-dev

sphinx:
  configuration: doc/source/conf.py

formats: all

python:
  version: 3.8
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt
